# Generated by Django 2.1.7 on 2019-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dependents', models.IntegerField(default=0)),
                ('applicant_income', models.IntegerField(default=0)),
                ('coapplicant_income', models.IntegerField(default=0)),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_amount_term', models.IntegerField(default=0)),
                ('credit_history', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'N/A')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('property_area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
